CREATE TABLE EMPLOYEES (
  ID NUMBER NOT NULL,
  NAME VARCHAR2(255) NOT NULL,
  DEPARTMENT VARCHAR2(255) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE EMPLOYEE_ID_SEQ;

INSERT INTO EMPLOYEES (ID, NAME, DEPARTMENT) VALUES (EMPLOYEE_ID_SEQ.nextval, '山田', '第一営業部');
INSERT INTO EMPLOYEES (ID, NAME, DEPARTMENT) VALUES (EMPLOYEE_ID_SEQ.nextval, '田中', '開発部');
INSERT INTO EMPLOYEES (ID, NAME, DEPARTMENT) VALUES (EMPLOYEE_ID_SEQ.nextval, '佐藤', '第二営業部');
INSERT INTO EMPLOYEES (ID, NAME, DEPARTMENT) VALUES (EMPLOYEE_ID_SEQ.nextval, '伊藤', '第一営業部');
INSERT INTO EMPLOYEES (ID, NAME, DEPARTMENT) VALUES (EMPLOYEE_ID_SEQ.nextval, '渡辺', '総務部');
INSERT INTO EMPLOYEES (ID, NAME, DEPARTMENT) VALUES (EMPLOYEE_ID_SEQ.nextval, '清水', '開発部');

